version: 2.1
executors:
  browser-executor:
    docker:
      - image: circleci/node:20-browsers
    working_directory: ~/repo
jobs:
  build:
    executor: browser-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  test:
    executor: browser-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Audit
          command: npm audit --audit-level=low --production
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
